# Generated by Django 4.1 on 2023-12-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
